var corp = "Corp",
	runner = "Runner",
	identity = "Identity",
	agenda = "Agenda",
	asset = "Asset",
	ice = "ICE",
	operation = "Operation",
	upgrade = "Upgrade",
	event = "Event",
	hardware = "Hardware",
	program = "Program",
	resource = "Resource",
	hb = "Haas-Bioroid",
	jin = "Jinteki",
	nbn = "NBN",
	wey = "Weyland Consortium",
	ana = "Anarch",
	crim = "Criminal",
	shap = "Shaper",
	neut = "Neutral",
	cardTypes = {},
	factions = {},
	sides = {};

sides[corp] = { name: "Corp", cardTypes: {}, factions: {} };
sides[runner] = { name: "Runner", cardTypes: {}, factions: {} };
sides[corp].cardTypes = [ identity, agenda, asset, ice, operation, upgrade ];
sides[runner].cardTypes = [ identity, event, hardware, program, resource ];
sides[corp].factions = [ hb, jin, nbn, wey, neut ];
sides[runner].factions = [ ana, crim, shap, neut ];
sides[corp].maxInfluence = 5;
sides[runner].maxInfluence = 5;
